import { User, UserRoleEnum } from '@/types/user';

export const MOCK_USER_DATA: User = {
  email: 'test@gmail.com',
  firstname: 'Ivan',
  lastname: 'Ivanov',
  roles: [UserRoleEnum.Admin],
  userId: '1',
};

export const MOCK_USERS_DATA = [
  {
    email: 'user1@example.com',
    balance: 15075,
    telegram: '@user1_telegram',
    price: 123231,
    userId: '123',
    discount: 0,
  },
  {
    email: 'user2@example.com',
    balance: 32050,
    telegram: '@user2_telegram',
    price: 123231,
    userId: '2',
    discount: 0,
  },
  {
    email: 'user3@example.com',
    balance: 5000,
    telegram: '@user3_telegram',
    price: 123231,
    userId: '3',
    discount: 0,
  },
  {
    email: 'user4@example.com',
    balance: 1000,
    telegram: '@user4_telegram',
    price: 123231,
    userId: '4',
    discount: 0,
  },
  {
    email: 'user5@example.com',
    balance: 100000,
    telegram: '@user5_telegram',
    price: 123231,
    userId: '5',
    discount: 0,
  },
  {
    email: 'user6@example.com',
    balance: 50025,
    telegram: '@user6_telegram',
    price: 123231,
    userId: '6',
    discount: 0,
  },
  {
    email: 'user7@example.com',
    balance: 7550,
    telegram: '@user7_telegram',
    price: 123231,
    userId: '7',
    discount: 0,
  },
  {
    email: 'user8@example.com',
    balance: 25000,
    telegram: '@user8_telegram',
    price: 123231,
    userId: '8',
    discount: 0,
  },
  {
    email: 'user9@example.com',
    balance: 43075,
    telegram: '@user9_telegram',
    price: 123231,
    userId: '9',
    discount: 0,
  },
  {
    email: 'user10@example.com',
    balance: 11050,
    telegram: '@user10_telegram',
    price: 123231,
    userId: '10',
    discount: 0,
  },
  {
    email: 'user11@example.com',
    balance: 11050,
    telegram: '@user10_telegram',
    price: 123231,
    userId: '11',
    discount: 0,
  },
  {
    email: 'user12@example.com',
    balance: 11050,
    telegram: '@user10_telegram',
    price: 123231,
    userId: '12',
    discount: 0,
  },
];
