import { UserList } from './getUserList';

export const MOCK_USER_LIST: UserList = [
  {
    userId: '1',
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    otherBalance: 15075,
    individualPricing: true,
  },
  {
    userId: '2',
    email: 'jane.smith@example.com',
    firstName: 'Jane',
    lastName: 'Smith',
    otherBalance: 2000,
    individualPricing: false,
  },
  {
    userId: '3',
    email: 'alice.jones@example.com',
    firstName: 'Alice',
    lastName: 'Jones',
    otherBalance: 3005,
    individualPricing: true,
  },
  {
    userId: '4',
    email: 'bob.brown@example.com',
    firstName: 'Bob',
    lastName: 'Brown',
    otherBalance: 5015,
    individualPricing: false,
  },
  {
    userId: '5',
    email: 'carol.white@example.com',
    firstName: 'Carol',
    lastName: 'White',
    otherBalance: 4000,
    individualPricing: true,
  },
  {
    userId: '6',
    email: 'david.green@example.com',
    firstName: 'David',
    lastName: 'Green',
    otherBalance: 1255,
    individualPricing: false,
  },
  {
    userId: '7',
    email: 'eve.adams@example.com',
    firstName: 'Eve',
    lastName: 'Adams',
    otherBalance: 1750,
    individualPricing: true,
  },
  {
    userId: '8',
    email: 'frank.miller@example.com',
    firstName: 'Frank',
    lastName: 'Miller',
    otherBalance: 22575,
    individualPricing: false,
  },
  {
    userId: '9',
    email: 'grace.hall@example.com',
    firstName: 'Grace',
    lastName: 'Hall',
    otherBalance: 3500,
    individualPricing: true,
  },
  {
    userId: '10',
    email: 'harry.wilson@example.com',
    firstName: 'Harry',
    lastName: 'Wilson',
    otherBalance: 1000,
    individualPricing: false,
  },
];
